version: '3.8'
services:
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - 4040:4040
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    depends_on:
      - webui
      - nginx

  ollama:
    image: ollama/ollama
    volumes:
      - /Users/tongcc/.ollama/models:/Users/tongcc/.ollama/models
    ports:
      - "11434:11434"

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://localhost:11434/api
    volumes:
      - webui_data:/app/backend/data
      - ollama_models:/app/backend/ollama_models
    depends_on:
      - ollama

  nginx:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  ollama_models:
  webui_data:
